version: '3'

services:
    
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:8080"
      # - "5432"
      - "443:443"
    volumes:
      - .:/code
      # - ./nginx:/etc/nginx/conf.d
      - ./frontend:/var/www/frontend
    depends_on:
      - backend
      
  db:
    restart: unless-stopped
    image: postgres:10.1-alpine
    # ports: 
    #   - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql

  backend:
    build: .
    depends_on:
      - db
    # command: bash -c "cd ocenka &&
    #                   python manage.py migrate &&
    #                   python manage.py makemigrations --no-input &&
    #                   python manage.py test jobs.tests.test_models"

    restart: unless-stopped
    command: bash -c "cd ocenka && 
                      python manage.py makemigrations --no-input &&
                      python manage.py migrate &&
                      python manage.py collectstatic --no-input &&
                      gunicorn ocenka.wsgi -b 0.0.0.0:8000"
   
    volumes:
      - .:/code
    ports:
      - "8000"
         
# volumes:
  # postgres_data:
